var texas;
(function (texas) {
    var EventCode;
    (function (EventCode) {
        EventCode[EventCode["ENTER_GAME"] = 0] = "ENTER_GAME";
        EventCode[EventCode["SIT_DOWN"] = 1] = "SIT_DOWN";
        EventCode[EventCode["SEND_PLAYER_CARDS"] = 2] = "SEND_PLAYER_CARDS";
        EventCode[EventCode["QUIT_GAME"] = 3] = "QUIT_GAME";
        EventCode[EventCode["GAME_CMD_TURN"] = 4] = "GAME_CMD_TURN";
        EventCode[EventCode["GAME_CMD_RIVER"] = 5] = "GAME_CMD_RIVER";
        EventCode[EventCode["GAME_CMD_SHOWDOWN"] = 6] = "GAME_CMD_SHOWDOWN";
        EventCode[EventCode["TURN_PLAYER"] = 7] = "TURN_PLAYER";
        EventCode[EventCode["STAND_UP"] = 8] = "STAND_UP";
        EventCode[EventCode["PUBLIC_CARDS"] = 9] = "PUBLIC_CARDS";
        EventCode[EventCode["PLAYER_OP"] = 10] = "PLAYER_OP";
        EventCode[EventCode["GAME_START"] = 11] = "GAME_START";
        EventCode[EventCode["SUB_POOL"] = 12] = "SUB_POOL";
        EventCode[EventCode["GAME_RESULT"] = 13] = "GAME_RESULT";
        EventCode[EventCode["UPDATE_PLAYER_STATUS"] = 14] = "UPDATE_PLAYER_STATUS";
        EventCode[EventCode["SHOW_MAX_CARDS"] = 15] = "SHOW_MAX_CARDS";
        EventCode[EventCode["TABLE_CHAT"] = 16] = "TABLE_CHAT";
        EventCode[EventCode["CHANGE_TABLE_OWNER"] = 17] = "CHANGE_TABLE_OWNER";
        EventCode[EventCode["SET_GAME_AUTO_START"] = 18] = "SET_GAME_AUTO_START";
        EventCode[EventCode["SHOW_CARDS"] = 19] = "SHOW_CARDS";
        EventCode[EventCode["KICK_PLAYER"] = 20] = "KICK_PLAYER";
        EventCode[EventCode["TASK_LIST"] = 21] = "TASK_LIST";
        EventCode[EventCode["RECIVED_TASK_REWARD"] = 22] = "RECIVED_TASK_REWARD";
        EventCode[EventCode["MAGIC_FACE"] = 23] = "MAGIC_FACE";
        EventCode[EventCode["TABLE_WIN_RECORD"] = 24] = "TABLE_WIN_RECORD";
        EventCode[EventCode["PLAYER_BASE_INFO"] = 25] = "PLAYER_BASE_INFO";
        EventCode[EventCode["SNG_UPDATE"] = 26] = "SNG_UPDATE";
        EventCode[EventCode["SNG_GRADE"] = 27] = "SNG_GRADE";
        EventCode[EventCode["HALL_INFO_UPDATE"] = 28] = "HALL_INFO_UPDATE";
        EventCode[EventCode["UPDATE_GOLD"] = 29] = "UPDATE_GOLD";
        EventCode[EventCode["SLOTS"] = 30] = "SLOTS";
        EventCode[EventCode["DICE"] = 31] = "DICE";
        EventCode[EventCode["SLOTS_STOP"] = 32] = "SLOTS_STOP";
        EventCode[EventCode["GAME_SETTLEMENT"] = 33] = "GAME_SETTLEMENT";
        EventCode[EventCode["PLAYER_DEPOSIT"] = 34] = "PLAYER_DEPOSIT";
    })(EventCode = texas.EventCode || (texas.EventCode = {}));
})(texas || (texas = {}));
